### ISSUE TITLE
Permission Request Dialog NOT Shown

### ISSUE THREAD

**Issue by halfcupCn** [googlesamples/easypermissions#118]
I follow the sample ask for `Manifest.permission.READ_SMS` permission with 
```
@AfterPermissionGranted(500)
    public void getSMS() {
        if (EasyPermissions.hasPermissions(this, Manifest.permission.READ_SMS)) {
            Log.v("TAG", "another way!");
        } else {
            Log.v("TAG", "another way failed!");
            EasyPermissions.requestPermissions(this, "i need permission to work TnT", 500, Manifest.permission.READ_SMS);
        }
    }
```
but this code didn't work in my phone Red MI Note 4 os 6.0 MIUI 7.5.11 & crashed in MI 3 os 6.0.1 CyanogenMod 13.0.
the crash stacktrace is
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.packageinstaller/com.android.packageinstaller.permission.ui.GrantPermissionsActivity}: java.lang.NullPointerException: Attempt to get length of null array
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2450)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510)
                                                       at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5461)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                    Caused by: java.lang.NullPointerException: Attempt to get length of null array
                                                       at com.android.packageinstaller.permission.ui.GrantPermissionsActivity.computePermissionGrantState(GrantPermissionsActivity.java:298)
                                                       at com.android.packageinstaller.permission.ui.GrantPermissionsActivity.updateDefaultResults(GrantPermissionsActivity.java:348)
                                                       at com.android.packageinstaller.permission.ui.GrantPermissionsActivity.onCreate(GrantPermissionsActivity.java:106)
                                                       at android.app.Activity.performCreate(Activity.java:6251)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510) 
                                                       at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:148) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5461) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```
with debug,i found it called `Activity#requestPermission`,but NO Permission Request Dialog shown,are there something wrong with my code or just bug?

**Comment by samtstern** [comment]
@halfcupCn what happened on the Redmi Note phone?  The crash on CyanogenMod does not seem like something we can prevent, custom ROMs often interfere with permission logic.

**Comment by socialvanana** [comment]
Did you put a line in the Manifest file?
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

**Comment by samtstern** [comment]
This issue has been inactive for a while, I am going to close it.  If you still need help just respond and I will re-open it.
