### ISSUE TITLE
出现一个空指针，不知如何复现这个问题

### ISSUE THREAD

**Issue by coolspan** [googlesamples/easypermissions#136]
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xxx/pub.devrel.easypermissions.AppSettingsDialogHolderActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void pub.devrel.easypermissions.AppSettingsDialog.a(android.content.Context)' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3319)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415)
       at android.app.ActivityThread.access$1100(ActivityThread.java:229)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7325)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void pub.devrel.easypermissions.AppSettingsDialog.a(android.content.Context)' on a null object reference
       at pub.devrel.easypermissions.AppSettingsDialogHolderActivity.onCreate(AppSettingsDialogHolderActivity.java:22)
       at android.app.Activity.performCreate(Activity.java:6904)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3266)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415)
       at android.app.ActivityThread.access$1100(ActivityThread.java:229)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7325)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by samtstern** [comment]
@coolspan can you show some code that leads to this issue?  And give some more information about your environment, mostly what device / Android version you're running.

Also please note I can only support issues written entirely in English, it's my only language.

**Comment by samtstern** [comment]
Closing due to lack of response.

**Comment by hoelee** [comment]
I have similar to this null pointer issue, I solved myself... 
Found out actually I override my manifests, please take note "replace" keyword below is override everything, therefore this plugin can't find the declare activity of "pub.devrel.easypermissions.AppSettingsDialogHolderActivity". 

<application
        tools:node="replace"
        xxx>
    <activity xxx></activity>
</application>

If you want override something, be specific like below just override label:
<application
        tools:overrideLibrary="com.xxxx.tobe.override.plugin"
        tools:replace="android:label"
        android:label="@string/app_name"
        xxx>
    <activity xxx></activity>
</application>

**Comment by hoelee** [comment]
I have similar to this null pointer issue, I solved myself... 
Found out actually I override my manifests, please take note "replace" keyword below is override everything, therefore this plugin can't find the declare activity of "pub.devrel.easypermissions.AppSettingsDialogHolderActivity". 

```
<application
        tools:node="replace"
        xxx>
    <activity xxx></activity>
</application>
```

If you want override something, be specific like below just override label:
```
<application
        tools:overrideLibrary="com.xxxx.tobe.override.plugin"
        tools:replace="android:label"
        android:label="@string/app_name"
        xxx>
    <activity xxx></activity>
</application>
```
