### ISSUE TITLE
Can not perform this action after onSaveInstanceState

### ISSUE THREAD

**Issue by jnam90** [googlesamples/easypermissions#150]
Using version 0.4.3. I am sometimes seeing this crash in production:

Fatal Exception: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
       at android.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1433)
       at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1451)
       at android.app.BackStackRecord.commitInternal(BackStackRecord.java:687)
       at android.app.BackStackRecord.commit(BackStackRecord.java:663)
       at android.app.DialogFragment.show(DialogFragment.java:230)
       at pub.devrel.easypermissions.helper.BaseFrameworkPermissionsHelper.showRequestPermissionRationale(BaseFrameworkPermissionsHelper.java:30)
       at pub.devrel.easypermissions.helper.PermissionHelper.requestPermissions(PermissionHelper.java:73)
       at pub.devrel.easypermissions.EasyPermissions.requestPermissions(EasyPermissions.java:183)
       at pub.devrel.easypermissions.EasyPermissions.requestPermissions(EasyPermissions.java:141)
       at com.xxx.xxx.xxx.xxx.BaseActivity.requestPermission(BaseActivity.java:333)

Device: Galaxy J5(2016)
OS: 6.0.1

**Comment by SUPERCILEX** [comment]
@jnam90 that means you are trying to request the permission after the activity is no longer visible. My guess is that you have the permission request is an async callback?

**Comment by SUPERCILEX** [comment]
@jnam90 Just another thought, are you [calling `super.onActivityResult()`](https://stackoverflow.com/a/30429551/4548500) in your activity?

**Comment by jnam90** [comment]
@SUPERCILEX  Sorry I saw last comment too late.

**Comment by samtstern** [comment]
This is pretty old and was closed once before by @jnam90 so I am going to close it again.  If anyone else experiences this issue on a recent version please file a new issue.
