### ISSUE TITLE
NoClassDefFoundError: android.view.DragAndDropPermissions

### ISSUE THREAD

**Issue by Martin-Hogge** [googlesamples/easypermissions#163]
When asking the user to accept the storage permission, it crashes with the following stacktrace:

```
Fatal Exception: java.lang.NoClassDefFoundError: android.view.DragAndDropPermissions
       at libcore.reflect.InternalNames.getClass(InternalNames.java:55)
       at java.lang.Class.getDexCacheType(Class.java:476)
       at java.lang.reflect.Method.getReturnType(Method.java:183)
       at java.lang.Class.getDeclaredMethods(Class.java:672)
       at pub.devrel.easypermissions.EasyPermissions.runAnnotatedMethods(EasyPermissions.java:362)
       at pub.devrel.easypermissions.EasyPermissions.onRequestPermissionsResult(EasyPermissions.java:236)
       at be.aedes.cerhis.base.BaseActivity.onRequestPermissionsResult(BaseActivity.java:517)
       at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7291)
       at android.app.Activity.dispatchActivityResult(Activity.java:7169)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4994)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5041)
       at android.app.ActivityThread.access$1600(ActivityThread.java:229)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1875)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7325)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by java.lang.ClassNotFoundException: Didn't find class "android.view.DragAndDropPermissions" on path: DexPathList[[zip file "/data/app/be.aedes.cerhis-2/base.apk"],nativeLibraryDirectories=[/data/app/be.aedes.cerhis-2/lib/arm, /data/app/be.aedes.cerhis-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
       at libcore.reflect.InternalNames.getClass(InternalNames.java:53)
       at java.lang.Class.getDexCacheType(Class.java:476)
       at java.lang.reflect.Method.getReturnType(Method.java:183)
       at java.lang.Class.getDeclaredMethods(Class.java:672)
       at pub.devrel.easypermissions.EasyPermissions.runAnnotatedMethods(EasyPermissions.java:362)
       at pub.devrel.easypermissions.EasyPermissions.onRequestPermissionsResult(EasyPermissions.java:236)
       at be.aedes.cerhis.base.BaseActivity.onRequestPermissionsResult(BaseActivity.java:517)
       at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7291)
       at android.app.Activity.dispatchActivityResult(Activity.java:7169)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4994)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5041)
       at android.app.ActivityThread.access$1600(ActivityThread.java:229)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1875)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7325)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

I'm using 1.0.0 version of the library and this crash happens on 6.0.1 android devices. 
I don't get what is wrong here.

**Comment by samtstern** [comment]
Thanks for the report @Martin-Hogge.  Is your app proguarded?  If so, does this issue also happen on debug builds?

**Comment by Martin-Hogge** [comment]
Sorry I missed you're comment. yes my app is proguarded but it happens on both builds: release and debug.

**Comment by Martin-Hogge** [comment]
On another device I got almost the same issue but with PictureInPicture class not found:

```
java.lang.NoClassDefFoundError: android.app.PictureInPictureParams
	 at libcore.reflect.InternalNames.getClass(InternalNames.java:55)
	 at java.lang.Class.getDexCacheType(Class.java:2551)
	 at java.lang.reflect.AbstractMethod.getParameterTypes(AbstractMethod.java:169)
	 at java.lang.reflect.Method.getParameterTypes(Method.java:193)
	 at java.lang.Class.getDeclaredMethods(Class.java:1812)
	 at pub.devrel.easypermissions.EasyPermissions.runAnnotatedMethods(EasyPermissions.java:368)
	 at pub.devrel.easypermissions.EasyPermissions.onRequestPermissionsResult(EasyPermissions.java:240)
	 at be.aedes.cerhis.base.BaseActivity.onRequestPermissionsResult(BaseActivity.java:519)
	 at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7458)
	 at android.app.Activity.dispatchActivityResult(Activity.java:7284)
	 at android.app.ActivityThread.deliverResults(ActivityThread.java:4516)
	 at android.app.ActivityThread.handleSendResult(ActivityThread.java:4563)
	 at android.app.ActivityThread.-wrap22(ActivityThread.java)
	 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1698)
	 at android.os.Handler.dispatchMessage(Handler.java:102)
	 at android.os.Looper.loop(Looper.java:154)
	 at android.app.ActivityThread.main(ActivityThread.java:6776)
	 at java.lang.reflect.Method.invoke(Native Method)
	 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
	 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
Caused by: java.lang.ClassNotFoundException: Didn't find class "android.app.PictureInPictureParams" on path: DexPathList[[zip file "/data/app/be.aedes.cerhis.aedes.debug-2/base.apk", zip file "/data/app/be.aedes.cerhis.aedes.debug-2/split_lib_dependencies_apk.apk", zip file "/data/app/be.aedes.cerhis.aedes.debug-2/split_lib_slice_0_apk.apk", zip file "/data/app/be.aedes.cerhis.aedes.debug-2/split_lib_slice_1_apk.apk", zip file "/data/app/be.aedes.cerhis.aedes.debug-2/split_lib_slice_2_apk.apk", zip file "/data/app/be.aedes.cerhis.aedes.debug-2/split_lib_slice_3_apk.apk", zip file "/data/app/be.aedes.cerhis.aedes.debug-2/split_lib_slice_4_apk.apk", zip file "/data/app/be.aedes.cerhis.aedes.debug-2/split_lib_slice_5_apk.apk", zip file "/data/app/be.aedes.cerhis.aedes.debug-2/split_lib_slice_6_apk.apk", zip file "/data/app/be.aedes.cerhis.aedes.debug-2/split_lib_slice_7_apk.apk", zip file "/data/app/be.aedes.cerhis.aedes.debug-2/split_lib_slice_8_apk.apk", zip file "/data/app/be.aedes.cerhis.aedes.debug-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/be.aedes.cerhis.aedes.debug-2/lib/arm, /data/app/be.aedes.cerhis.aedes.debug-2/base.apk!/lib/armeabi-v7a, /data/app/be.aedes.cerhis.aedes.debug-2/split_lib_dependencies_apk.apk!/lib/armeabi-v7a, /data/app/be.aedes.cerhis.aedes.debug-2/split_lib_slice_0_apk.apk!/lib/armeabi-v7a, /data/app/be.aedes.cerhis.aedes.debug-2/split_lib_slice_1_apk.apk!/lib/armeabi-v7a, /data/app/be.aedes.cerhis.aedes.debug-2/split_lib_slice_2_apk.apk!/lib/armeabi-v7a, /data/app/be.aedes.cerhis.aedes.debug-2/split_lib_slice_3_apk.apk!/lib/armeabi-v7a, /data/app/be.aedes.cerhis.aedes.debug-2/split_lib_slice_4_apk.apk!/lib/armeabi-v7a, /data/app/be.aedes.cerhis.aedes.debug-2/split_lib_slice_5_apk.apk!/lib/armeabi-v7a, /data/app/be.aedes.cerhis.aedes.debug-2/split_lib_slice_6_apk.apk!/lib/armeabi-v7a, /data/app/be.aedes.cerhis.aedes.debug-2/split_lib_slice_7_apk.apk!/lib/armeabi-v7a, /data/app/be.aedes.cerhis.aedes.debug-2/split_lib_slice_8_apk.apk!/lib/armeabi-v7a, /data/app/be.aedes.cerhis.aedes.debug-2/split_lib_slice_9_apk.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
	 at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	 at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
	 at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	 at libcore.reflect.InternalNames.getClass(InternalNames.java:53)
	 at java.lang.Class.getDexCacheType(Class.java:2551) 
	 at java.lang.reflect.AbstractMethod.getParameterTypes(AbstractMethod.java:169) 
	 at java.lang.reflect.Method.getParameterTypes(Method.java:193) 
	 at java.lang.Class.getDeclaredMethods(Class.java:1812) 
	 at pub.devrel.easypermissions.EasyPermissions.runAnnotatedMethods(EasyPermissions.java:368) 
	 at pub.devrel.easypermissions.EasyPermissions.onRequestPermissionsResult(EasyPermissions.java:240) 
	 at be.aedes.cerhis.base.BaseActivity.onRequestPermissionsResult(BaseActivity.java:519) 
	 at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7458) 
	 at android.app.Activity.dispatchActivityResult(Activity.java:7284) 
	 at android.app.ActivityThread.deliverResults(ActivityThread.java:4516) 
	 at android.app.ActivityThread.handleSendResult(ActivityThread.java:4563) 
	 at android.app.ActivityThread.-wrap22(ActivityThread.java) 
	 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1698) 
	 at android.os.Handler.dispatchMessage(Handler.java:102) 
	 at android.os.Looper.loop(Looper.java:154) 
	 at android.app.ActivityThread.main(ActivityThread.java:6776) 
	 at java.lang.reflect.Method.invoke(Native Method) 
	 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496) 
	 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
                                                                                 
```

**Comment by samtstern** [comment]
@Martin-Hogge I apologize for the lack of response but I don't think this has anything to do with EasyPermissions since the failures are in a framework class `android.app.PictureInPictureParams` which is completely outside our control.
