### ISSUE TITLE
java.lang.RuntimeException: Cannot execute method requestPhone because it is non-void method and/or has input parameters.

### ISSUE THREAD

**Issue by sheng930920** [googlesamples/easypermissions#228]
## java.lang.RuntimeException: Cannot execute method requestPhone because it is non-void method and/or has input parameters.

Device type: samsung
OS version: SM-J250F  Android7.1.1
EasyPermissions version: 1.2.0

## Describe the problem

I Have tried to add the Call permission in Activity it will getting crashed the initial time after that it will working fine, the same code in activity working always fine.

## Code and logs

```
@AfterPermissionGranted(PHONE_PERMISSION)
    private void requestPhone(String phoneNum) {
        if (EasyPermissions.hasPermissions(this, Manifest.permission.CALL_PHONE)) {
            call(phoneNum);
        } else {
            EasyPermissions.requestPermissions(this, "", PHONE_PERMISSION, Manifest.permission.CALL_PHONE);
        }
    }

@Override
    public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions, @NonNull int[] grantResults) {
        super.onRequestPermissionsResult(requestCode, permissions, grantResults);
        EasyPermissions.onRequestPermissionsResult(requestCode, permissions, grantResults, this);
    }

    @Override
    public boolean shouldShowRequestPermissionRationale(String permission) {
        return false;
    }


java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=1, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS launchParam=MultiScreenLaunchParams { mDisplayId=0 mBaseDisplayId=0 mFlags=0 } (has extras) }} to activity {com.gosstech.expressdriver/com.gosstech.expressdriver.activity.delivery.DeliveryActivity}: java.lang.RuntimeException: Cannot execute method requestPhone because it is non-void method and/or has input parameters.
at android.app.ActivityThread.deliverResults(ActivityThread.java:4556)
at android.app.ActivityThread.handleSendResult(ActivityThread.java:4599)
at android.app.ActivityThread.-wrap22(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1715)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6816)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1565)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1453)
Caused by: java.lang.RuntimeException: Cannot execute method requestPhone because it is non-void method and/or has input parameters.
at pub.devrel.easypermissions.EasyPermissions.runAnnotatedMethods(EasyPermissions.java:421)
at pub.devrel.easypermissions.EasyPermissions.onRequestPermissionsResult(EasyPermissions.java:285)
at com.gosstech.expressdriver.activity.delivery.DeliveryActivity.onRequestPermissionsResult(DeliveryActivity.java:328)
at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7515)
at android.app.Activity.dispatchActivityResult(Activity.java:7341)
at android.app.ActivityThread.deliverResults(ActivityThread.java:4552)

**Comment by samtstern** [comment]
The AfterPermissionGranted annotation can only be used with methods that take no parameters.  Your request phone method takes a string.
