### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by YouJZ** [googlesamples/easypermissions#278]
## Basic Information

Device type: __huawei______
OS version: __android 6.0______
EasyPermissions version: ____2.0.1____

## Describe the problem

What happened?  What did you expect to happen?
when I call AppSettingsDialog show
## Code and logs

java.lang.RuntimeException:Unable to start activity ComponentInfo{com.qiushibaike.inews/pub.devrel.easypermissions.AppSettingsDialogHolderActivity}: java.lang.NullPointerException: Attempt to invoke direct method 'void vy.֏(java.lang.Object)' on a null object reference
--
2 android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2479)
3 ......
4 Caused by:
5 java.lang.NullPointerException:Attempt to invoke direct method 'void vy.֏(java.lang.Object)' on a null object reference
6 vy.֏(AppSettingsDialog.java:85)
7 pub.devrel.easypermissions.AppSettingsDialogHolderActivity.onCreate(AppSettingsDialogHolderActivity.java:31)
8 android.app.Activity.performCreate(Activity.java:6372)

```
// TODO(you): show the code that produces the problem,
//            and any relevant logs.
```

**Comment by samtstern** [comment]
@YouJZ I'm not quite sure where to start with this one, especially since it looks like you're using an obfuscator which causes your method names to become symbols: `void vy.֏`

Are you able to reproduce this easily on a local device?

**Comment by artakka** [comment]
@samtstern This may be the same crash, without obfuscation. I got it during a stress test.

```
Caused by java.lang.NullPointerException
Attempt to invoke direct method 'void pub.devrel.easypermissions.AppSettingsDialog.setActivityOrFragment(java.lang.Object)' on a null object reference

Caused by java.lang.NullPointerException: Attempt to invoke direct method 'void pub.devrel.easypermissions.AppSettingsDialog.setActivityOrFragment(java.lang.Object)' on a null object reference
       at pub.devrel.easypermissions.AppSettingsDialog.fromIntent(AppSettingsDialog.java)
       at pub.devrel.easypermissions.AppSettingsDialogHolderActivity.onCreate(AppSettingsDialogHolderActivity.java)
       at android.app.Activity.performCreate(Activity.java:6679)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6119)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
```

**Comment by samtstern** [comment]
@artakka thanks for that stack trace!  Will be very useful.

**Comment by NewHuLe** [comment]
@samtstern This may be the same crash, What should I do？
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mysteel.android.steelphone/pub.devrel.easypermissions.AppSettingsDialogHolderActivity}: java.lang.NullPointerException: Attempt to invoke direct method 'void pub.devrel.easypermissions.

Caused by: java.lang.NullPointerException: Attempt to invoke direct method 'void pub.devrel.easypermissions.AppSettingsDialog.a(java.lang.Object)' on a null object reference
at pub.devrel.easypermissions.AppSettingsDialog.fromIntent(AppSettingsDialog.java)
setActivityOrFragment
startForResult
show
showDialog
at pub.devrel.easypermissions.AppSettingsDialogHolderActivity.onCreate(Native Method)
at android.app.Activity.performCreate(Activity.java:6372)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2432)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2539)
at android.app.ActivityThread.access$900(ActivityThread.java:168)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1378)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:150)
at android.app.ActivityThread.main(ActivityThread.java:5659)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:822)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712)
```

**Comment by jaragones** [comment]
I'm also having similar issue (2 reports on Fabric). Any solution? Thanks!

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.zynbit.app/pub.devrel.easypermissions.AppSettingsDialogHolderActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void pub.devrel.easypermissions.AppSettingsDialog.setContext(android.content.Context)' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6119)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
```


```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.zynbit.app/net.openid.appauth.RedirectUriReceiverActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getQueryParameter(java.lang.String)' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6119)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
```

**Comment by cgpllx** [comment]
Caused by java.lang.NullPointerException: Attempt to invoke direct method 'void pub.devrel.easypermissions.AppSettingsDialog.setActivityOrFragment(java.lang.Object)' on a null object reference
       at pub.devrel.easypermissions.AppSettingsDialog.fromIntent + 81(AppSettingsDialog.java:81)
       at pub.devrel.easypermissions.AppSettingsDialogHolderActivity.onCreate + 29(AppSettingsDialogHolderActivity.java:29)
       at android.app.Activity.performCreate + 6280(Activity.java:6280)
       at android.app.Instrumentation.callActivityOnCreate + 1107(Instrumentation.java:1107)
       at android.app.ActivityThread.performLaunchActivity + 2372(ActivityThread.java:2372)
       at android.app.ActivityThread.handleLaunchActivity + 2479(ActivityThread.java:2479)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage + 1347(ActivityThread.java:1347)
       at android.os.Handler.dispatchMessage + 102(Handler.java:102)
       at android.os.Looper.loop + 148(Looper.java:148)
       at android.app.ActivityThread.main + 5420(ActivityThread.java:5420)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run + 726(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main + 616(ZygoteInit.java:616)

**Comment by Ucdemir** [comment]
Caused by java.lang.NullPointerException: Attempt to invoke direct method 'void pub.devrel.easypermissions.AppSettingsDialog.setActivityOrFragment(java.lang.Object)' on a null object reference
       at pub.devrel.easypermissions.AppSettingsDialog.fromIntent(AppSettingsDialog.java:86)
       at pub.devrel.easypermissions.AppSettingsDialogHolderActivity.onCreate(AppSettingsDialogHolderActivity.java:31)
       at android.app.Activity.performCreate(Activity.java:6280)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1116)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2372)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2479)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1347)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5421)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by Ucdemir** [comment]
any solution

**Comment by Ucdemir** [comment]
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{yazilim.hilal.yesil.studytimetable/pub.devrel.easypermissions.AppSettingsDialogHolderActivity}: java.lang.NullPointerException: Attempt to invoke direct method 'void pub.devrel.easypermissions.AppSettingsDialog.setActivityOrFragment(java.lang.Object)' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2419)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2479)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1347)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5421)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by caycek** [comment]
So this is still happening to Nexus 6 devices on Nougat (7.1.1). Did anyone determine what the actual cause of this is? I can't seem to figure out where the null comes from since the fragment / activities being used shouldn't be null when invoking the call.

**Comment by abhiint16** [comment]
Device : LGE Nexus 4
Version: 6.0.1
Rooted: No

`Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.project100pi.video.downloader.videodownloader/pub.devrel.easypermissions.AppSettingsDialogHolderActivity}: java.lang.NullPointerException: Attempt to write to field 'java.lang.Object v.a.a.b.l' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2419)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2479)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1347)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5421)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

**Comment by NaughtBoy** [comment]
Are this bug fixed?
