### ISSUE TITLE
SecurityException

### ISSUE THREAD

**Issue by SimonSchubert** [googlesamples/easypermissions#30]
I get the following error via crashlyics on a 5.1.1 Samsung SM-A710Y device. It's a one out of 10k. Anyone has an idea how that can happen?

Fatal Exception: java.lang.SecurityException
Client must have ACCESS_FINE_LOCATION permission to request PRIORITY_HIGH_ACCURACY locations.

```
String[] perms = {Manifest.permission.ACCESS_FINE_LOCATION, Manifest.permission.ACCESS_COARSE_LOCATION};
if (EasyPermissions.hasPermissions(this, perms)) {
     LocationServices.FusedLocationApi.requestLocationUpdates( mGoogleApiClient, mLocationRequest, this);
}
```

**Comment by samtstern** [comment]
@SimonSchubert on a 5.1.1 device there are no runtime permissions so EasyPermissions is likely not the problem.  Did you remember to add both of those permissions to your `AndroidManifest.xml`?

**Comment by SimonSchubert** [comment]
@samtstern Thank your for the help. 

Both permissions are in the manifest:
```
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
```

And I also got 6 users out of 10k with a 6.0.1 Android device. 5 x OnePlus A0001 and 1 x LeMobile Le X820. None of the devices are rooted. How can this happen and what should I do? Should I put an ugly SecurityException try and catch around the failing line?

**Comment by samtstern** [comment]
@SimonSchubert just to be totally sure:

  * Are your `<uses-permission>` elements **outside** of the `<application>` tag?
  * Are you using any other permissions in your app, and are you seeing any issues with those?

**Comment by SimonSchubert** [comment]
@samtstern yes both permissions are outside of the application tag. And I didn't see any issue like this with other permissions so far. It definitely works for 99.9% of the users. That is really weird. 

The whole Exception:

> Fatal Exception: java.lang.SecurityException: Client must have ACCESS_FINE_LOCATION permission to request PRIORITY_HIGH_ACCURACY locations.
       at android.os.Parcel.readException(Parcel.java:1620)
       at android.os.Parcel.readException(Parcel.java:1573)
       at com.google.android.gms.location.internal.zzi$zza$zza.zza(Unknown Source)
       at com.google.android.gms.location.internal.zzk.zza(Unknown Source)
       at com.google.android.gms.location.internal.zzl.zza(Unknown Source)
       at com.google.android.gms.location.internal.zzd$1.zza(Unknown Source)
       at com.google.android.gms.location.internal.zzd$1.zza(Unknown Source)
       at com.google.android.gms.internal.zzpr$zza.zzb(Unknown Source)
       at com.google.android.gms.internal.zzqa.zzf(Unknown Source)
       at com.google.android.gms.internal.zzqa.zzd(Unknown Source)
       at com.google.android.gms.internal.zzqf.zzd(Unknown Source)
       at com.google.android.gms.internal.zzqd.zzd(Unknown Source)
       at com.google.android.gms.location.internal.zzd.requestLocationUpdates(Unknown Source)
       at com.kptncook.app.kptncook.RecipeFlipperActivity.startLocationUpdates(RecipeFlipperActivity.java:34)
       at com.kptncook.app.kptncook.RecipeFlipperActivity.onConnected(RecipeFlipperActivity.java:60)
       at com.google.android.gms.common.internal.zzl.zzo(Unknown Source)
       at com.google.android.gms.internal.zzqd.zzm(Unknown Source)
       at com.google.android.gms.internal.zzqb.zzapm(Unknown Source)
       at com.google.android.gms.internal.zzqb.onConnected(Unknown Source)
       at com.google.android.gms.internal.zzqf.onConnected(Unknown Source)
       at com.google.android.gms.internal.zzpu.onConnected(Unknown Source)
       at com.google.android.gms.common.internal.zzk$1.onConnected(Unknown Source)
       at com.google.android.gms.common.internal.zzd$zzj.zzarz(Unknown Source)
       at com.google.android.gms.common.internal.zzd$zza.zzc(Unknown Source)
       at com.google.android.gms.common.internal.zzd$zza.zzx(Unknown Source)
       at com.google.android.gms.common.internal.zzd$zze.zzasb(Unknown Source)
       at com.google.android.gms.common.internal.zzd$zzd.handleMessage(Unknown Source)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5519)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by samtstern** [comment]
@SimonSchubert that's really strange ... unfortunately without a reproduction case and given that it works for 99.9% of users I'd say it has nothing to do with EasyPermissions.  This library just calls out to system APIs for checking and granting permissions, and on Android 5.1.1 those should be no-ops.

It's possible that your users have custom ROMs and are overriding certain permissions, but since you said they're not rooted even that is unlikely.

While I know we didn't solve it, I am going to close this issue since I am pretty powerless to help.  If you can reproduce on a common device or emulator I would be happy to re-open the investigation.

**Comment by Tortel** [comment]
The OnePlus One ships with CyanogenOS, which I believe allows users to disable permissions, even on 5.x

**Comment by SimonSchubert** [comment]
@samtstern ok it is safe to say that it doesn't have todo anything with the easypermissions library.

Thanks for the help. If anyone else has ideas, please let us know.

For now I will stick with the ugly try and catch solution.

@Tortel Ok this could explain the 5.x crash but not the 6.x, or?

**Comment by ekanshkaushik** [comment]
@SimonSchubert Were you able to figure this issue out ?
