### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewGroup$LayoutParams android.view.View.getLayoutParams()' on a null object reference

### ISSUE THREAD

**Issue by jhwsx** [googlesamples/easypermissions#311]
## Basic Information

EasyPermissions version: 3.0.0

## Describe the problem

I haven't reproduced this problem, which is reported online.

## Code and logs

```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewGroup$LayoutParams android.view.View.getLayoutParams()' on a null object reference
    at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3887)
    at android.os.Handler.dispatchMessage(Handler.java:105)
    at android.os.Looper.loop(Looper.java:156)
    at android.app.ActivityThread.main(ActivityThread.java:6605)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:999)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:889)
Back traces ends.
```

**Comment by samtstern** [comment]
@jhwsx so there's nothing in that stacktrace that references easypermissions, what makes you suspect this is a bug in the library?

**Comment by jhwsx** [comment]
The behavior trace of users is related to permission request process, which is backed by EP. Actually, I am not 100% sure that it is a problem of EP, which I, however, simply am apt to.
I will be sorry if it really isn't a problem of EP.

**Comment by jhwsx** [comment]
@samtstern Could you please help me exclude that it's a problem of EP?

**Comment by samtstern** [comment]
@jhwsx sorry given that you can't reproduce this in your own testing it's not going to be possible for me to debug it,.
