### ISSUE TITLE
Can't be used in Activity?

### ISSUE THREAD

**Issue by HuangShun** [googlesamples/easypermissions#90]
If i used it in activity.first i refused,then i open it, show a dialog i click confirm it crashed.if i use AppCompatActivity don't have this problem.
`        java.lang.ClassCastException: com.example.me.androdnewfeature.MainActivity cannot be cast to android.support.v4.app.FragmentActivity
        at pub.devrel.easypermissions.RationaleDialogClickListener.onClick(RationaleDialogClickListener.java:57)
        at android.support.v7.app.AlertController$ButtonHandler.handleMessage(AlertController.java:161)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)`

**Comment by piotrek1543** [comment]
@HuangShun I suppose that you're beginner in Android and you don't know difference between `Activity` and 'AppCompatActivity' and 'FragmentActivity'. I don't want to copy-paste someone's else answer, so please read carefully Commonsware answer: http://stackoverflow.com/a/31297546/4730812

**Comment by HuangShun** [comment]
@piotrek1543 Thank you

**Comment by SUPERCILEX** [comment]
This was fixed in #78, but a new version hasn't been released yet. @samtstern Any idea when a new version will come​ out?

**Comment by SUPERCILEX** [comment]
@samtstern SGTM!

**Comment by HuangShun** [comment]
thanks,I know how to do it @samtstern

**Comment by XuHX** [comment]
假设成功
