### ISSUE TITLE
Dialog leaked window

### ISSUE THREAD

**Issue by SethFeng** [googlesamples/easypermissions#97]
E/WindowManager: android.view.WindowLeaked: Activity pub.devrel.easypermissions.AppSettingsDialogHolderActivity has leaked window DecorView@e08daea[] that was originally added here
                                                                at android.view.ViewRootImpl.<init>(ViewRootImpl.java:418)
                                                                at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:331)
                                                                at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
                                                                at android.app.Dialog.show(Dialog.java:322)
                                                                at pub.devrel.easypermissions.AppSettingsDialog.showDialog(AppSettingsDialog.java:130)
                                                                at pub.devrel.easypermissions.AppSettingsDialogHolderActivity.onCreate(AppSettingsDialogHolderActivity.java:25)
                                                                at android.app.Activity.performCreate(Activity.java:6679)
                                                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                                at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                at android.os.Looper.loop(Looper.java:154)
                                                                at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by samtstern** [comment]
@SethFeng thanks for the report!  Do you have any steps to reproduce this?  I am going to guess it has to do with rotating the device when AppSettingsDialog is showing.

**Comment by samtstern** [comment]
Yep I reproduced by those steps.

**Comment by samtstern** [comment]
This is fixed by #115 and will be included in the next release (date TBD)
